import { ImageResponse } from "next/og"

import { SITE_NAME, SITE_TAGLINE } from "@/lib/seo"

// Default Open Graph image at 1200×630. Used by the root layout's
// `metadata.openGraph` when a child route doesn't provide its own.
//
// Per-route OG (e.g. blog posts, alternative pages) are generated by
// `app/og/route.tsx` with title/description query params.
export const alt = `${SITE_NAME} — ${SITE_TAGLINE}`
export const size = { width: 1200, height: 630 }
export const contentType = "image/png"

export default function OpengraphImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          padding: 80,
          background: "#fafaf9", // matches our warm-neutral surface-3 vibe
          color: "#262626",
        }}
      >
        {/* Top-left brand mark */}
        <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
          <div
            style={{
              width: 56,
              height: 56,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              background: "#262626",
              color: "white",
              fontSize: 36,
              fontWeight: 500,
              borderRadius: 12,
            }}
          >
            E
          </div>
          <div style={{ fontSize: 32, fontWeight: 500 }}>{SITE_NAME}</div>
        </div>

        {/* Tagline + thin divider */}
        <div style={{ display: "flex", flexDirection: "column", gap: 24 }}>
          <div
            style={{
              fontSize: 72,
              fontWeight: 500,
              lineHeight: 1.1,
              letterSpacing: "-0.02em",
              maxWidth: 900,
            }}
          >
            {SITE_TAGLINE}
          </div>
          <div
            style={{
              fontSize: 28,
              color: "#737373",
              maxWidth: 900,
              lineHeight: 1.4,
            }}
          >
            Collect feedback, prioritize features, share your roadmap. Free
            forever — no per-user pricing, ever.
          </div>
        </div>
      </div>
    ),
    { ...size },
  )
}
